import Foundation
import SwiftUI

class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()
    @Published var currentLanguage: String {
        didSet {
            updateTranslations()
        }
    }
    
    @Published var translations: [String: String] = [:]
    
    private init() {
        self.currentLanguage = UserPreferences.shared.selectedLanguage
        updateTranslations()
    }
    
    private func updateTranslations() {
        switch currentLanguage {
        case "fr":
            translations = [
                "form.title": "Créer un Profil",
                "form.subtitle": "Personnalisons le profil de votre enfant",
                "form.firstName": "Prénom",
                "form.firstName.placeholder": "Comment s'appelle l'enfant ?",
                "form.age": "Âge",
                "form.age.placeholder": "Quel âge a l'enfant ?",
                "form.age.years": "ans",
                "form.activity": "Activité préférée",
                "form.activity.placeholder": "Quelle activité aime-t-il faire ?",
                "form.passions": "Centres d'intérêt",
                "form.passions.placeholder": "Quelles sont ses passions ?",
                "form.message": "Message éducatif",
                "form.message.placeholder": "Quel message souhaitez-vous transmettre ?",
                "form.button": "Créer un profil",
                "form.save": "Sauvegarder le profil",
                "form.generate": "Générer une histoire",
                "form.generating": "Génération en cours...",
                "alert.error.title": "Oh non !",
                "alert.ok": "OK",
                "alert.retry": "Réessayer",
                "story.title": "Histoire Magique",
                "story.history": "Histoires de",
                "story.for": "Histoire de",
                "story.unique": "Une histoire unique, créée spécialement pour toi",
                "story.new": "Nouvelle version",
                "story.share": "Partager",
                "welcome.message": "Commençons l'aventure !",
                "settings.title": "Réglages",
                "settings.language": "Langue",
                "settings.done": "Terminé",
                "content.generate": "Créer une histoire",
                "content.edit": "Modifier",
                "form.photo": "Choisir une photo",
                "story.play": "Écouter l'histoire",
                "story.pause": "Pause",
                "story.generating.audio": "Génération de l'audio...",
                "story.select": "Lire l'histoire",
                "story.options.title": "Options de l'histoire",
                "story.options.cancel": "Annuler",
                "story.options.generate": "Générer",
                "story.length.title": "Longueur de l'histoire",
                "story.length.short": "Courte",
                "story.length.medium": "Moyenne",
                "story.length.long": "Longue",
                "story.length.words": "mots",
                "story.message.title": "Message à transmettre",
                "story.message.placeholder": "Quelle morale ou quel message souhaitez-vous transmettre ?",
            ]
        case "en":
            translations = [
                "form.title": "Create Profile",
                "form.subtitle": "Let's personalize your child's profile",
                "form.firstName": "First Name",
                "form.firstName.placeholder": "What's the child's name?",
                "form.age": "Age",
                "form.age.placeholder": "How old is the child?",
                "form.age.years": "years old",
                "form.activity": "Favorite Activity",
                "form.activity.placeholder": "What activity do they enjoy?",
                "form.passions": "Interests",
                "form.passions.placeholder": "What are their passions?",
                "form.message": "Educational Message",
                "form.message.placeholder": "What message would you like to convey?",
                "form.button": "Create Profile",
                "form.save": "Save Profile",
                "form.generate": "Generate Story",
                "form.generating": "Generating...",
                "alert.error.title": "Oh no!",
                "alert.ok": "OK",
                "alert.retry": "Retry",
                "story.title": "Magic Story",
                "story.history": "Stories of",
                "story.for": "Story for",
                "story.unique": "A unique story, created especially for you",
                "story.new": "New version",
                "story.share": "Share",
                "welcome.message": "Let's start the adventure!",
                "settings.title": "Settings",
                "settings.language": "Language",
                "settings.done": "Done",
                "content.generate": "Create Story",
                "content.edit": "Edit",
                "form.photo": "Choose a photo",
                "story.play": "Listen to story",
                "story.pause": "Pause",
                "story.generating.audio": "Generating audio...",
                "story.select": "Read story",
                "story.options.title": "Story Options",
                "story.options.cancel": "Cancel",
                "story.options.generate": "Generate",
                "story.length.title": "Story Length",
                "story.length.short": "Short",
                "story.length.medium": "Medium",
                "story.length.long": "Long",
                "story.length.words": "words",
                "story.message.title": "Message to Convey",
                "story.message.placeholder": "What moral or message would you like to convey?",
            ]
        case "es":
            translations = [
                "form.title": "Crear Perfil",
                "form.subtitle": "Vamos a personalizar el perfil de tu hijo",
                "form.firstName": "Nombre",
                "form.firstName.placeholder": "¿Cómo se llama el niño?",
                "form.age": "Edad",
                "form.age.placeholder": "¿Qué edad tiene el niño?",
                "form.age.years": "años",
                "form.activity": "Actividad Favorita",
                "form.activity.placeholder": "¿Qué actividad le gusta hacer?",
                "form.passions": "Intereses",
                "form.passions.placeholder": "¿Cuáles son sus pasiones?",
                "form.message": "Mensaje Educativo",
                "form.message.placeholder": "¿Qué mensaje quieres transmitir?",
                "form.button": "Crear Perfil",
                "form.save": "Guardar Perfil",
                "form.generate": "Generar Historia",
                "form.generating": "Generando...",
                "alert.error.title": "¡Oh no!",
                "alert.ok": "OK",
                "alert.retry": "Reintentar",
                "story.title": "Historia Mágica",
                "story.history": "Historias de",
                "story.for": "Historia para",
                "story.unique": "Una historia única, creada especialmente para ti",
                "story.new": "Nueva versión",
                "story.share": "Compartir",
                "welcome.message": "¡Empecemos la aventura!",
                "settings.title": "Ajustes",
                "settings.language": "Idioma",
                "settings.done": "Listo",
                "content.generate": "Crear Historia",
                "content.edit": "Editar",
                "form.photo": "Elegir una foto",
                "story.play": "Escuchar historia",
                "story.pause": "Pausa",
                "story.generating.audio": "Generando audio...",
                "story.select": "Leer historia",
                "story.options.title": "Opciones de la Historia",
                "story.options.cancel": "Cancelar",
                "story.options.generate": "Generar",
                "story.length.title": "Longitud de la Historia",
                "story.length.short": "Corta",
                "story.length.medium": "Media",
                "story.length.long": "Larga",
                "story.length.words": "palabras",
                "story.message.title": "Mensaje a Transmitir",
                "story.message.placeholder": "¿Qué moraleja o mensaje te gustaría transmitir?",
            ]
        case "ru":
            translations = [
                "form.title": "Создать профиль",
                "form.subtitle": "Давайте персонализируем профиль вашего ребенка",
                "form.firstName": "Имя",
                "form.firstName.placeholder": "Как зовут ребенка?",
                "form.age": "Возраст",
                "form.age.placeholder": "Сколько лет ребенку?",
                "form.age.years": "лет",
                "form.activity": "Любимое занятие",
                "form.activity.placeholder": "Какое занятие ему нравится?",
                "form.passions": "Интересы",
                "form.passions.placeholder": "Какие у него увлечения?",
                "form.message": "Воспитательное послание",
                "form.message.placeholder": "Какое послание вы хотите передать?",
                "form.button": "Создать профиль",
                "form.save": "Сохранить профиль",
                "form.generate": "Создать историю",
                "form.generating": "Создание...",
                "alert.error.title": "О нет!",
                "alert.ok": "OK",
                "alert.retry": "Повторить",
                "story.title": "Волшебная история",
                "story.history": "Истории",
                "story.for": "История для",
                "story.unique": "Уникальная история, созданная специально для тебя",
                "story.new": "Новая версия",
                "story.share": "Поделиться",
                "welcome.message": "Начнем приключение!",
                "settings.title": "Настройки",
                "settings.language": "Язык",
                "settings.done": "Готово",
                "content.generate": "Создать историю",
                "content.edit": "Изменить",
                "form.photo": "Выбрать фото",
                "story.play": "Слушать историю",
                "story.pause": "Пауза",
                "story.generating.audio": "Создание аудио...",
                "story.select": "Читать историю",
                "story.options.title": "Параметры Истории",
                "story.options.cancel": "Отмена",
                "story.options.generate": "Создать",
                "story.length.title": "Длина Истории",
                "story.length.short": "Короткая",
                "story.length.medium": "Средняя",
                "story.length.long": "Длинная",
                "story.length.words": "слов",
                "story.message.title": "Сообщение для Передачи",
                "story.message.placeholder": "Какую мораль или сообщение вы хотите передать?",
            ]
        default:
            translations = [:]
        }
    }
    
    func localizedString(_ key: String) -> String {
        return translations[key] ?? key
    }
} 