name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Build
      run: |
        cd enfants
        xcodebuild -scheme enfants -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 15' build
      
    - name: Test
      run: |
        cd enfants
        xcodebuild -scheme enfants -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 15' test 